comment on table document_metadata is '文档主数据表，保存文档归属、来源、存储定位与摘要状态。';
comment on column document_metadata.document_id is '文档内部主键，作为服务内稳定文档标识。';
comment on column document_metadata.tenant_id is '文档所属租户标识。';
comment on column document_metadata.owner_user is '文档归属用户标识。';
comment on column document_metadata.source_system is '文档来源系统标识，例如 native 或外部业务系统。';
comment on column document_metadata.external_document_id is '外部系统中的文档标识，用于与上游业务对象绑定。';
comment on column document_metadata.title is '文档展示标题。';
comment on column document_metadata.storage_key is '对象存储中的稳定对象键。';
comment on column document_metadata.file_type is '文件扩展类型，例如 docx。';
comment on column document_metadata.document_type is '文档业务类型，例如 word。';
comment on column document_metadata.status is '文档当前摘要状态，例如 draft、editing、saved、failed。';
comment on column document_metadata.last_callback_status is '最近一次 ONLYOFFICE callback 状态码。';
comment on column document_metadata.last_error_message is '最近一次保存或回调失败信息。';
comment on column document_metadata.created_time is '文档元数据创建时间。';
comment on column document_metadata.updated_time is '文档元数据最近更新时间。';
comment on column document_metadata.last_opened_time is '最近一次被打开的时间。';
comment on column document_metadata.last_callback_time is '最近一次收到 ONLYOFFICE callback 的时间。';
comment on column document_metadata.last_saved_time is '最近一次成功回写共享存储的时间。';

comment on table access_audit_event is '访问审计事件表，记录文档相关访问与操作审计轨迹。';
comment on column access_audit_event.event_id is '审计事件主键。';
comment on column access_audit_event.document_id is '关联的内部文档主键。';
comment on column access_audit_event.tenant_id is '触发审计事件的租户标识。';
comment on column access_audit_event.source_system is '触发操作的来源系统。';
comment on column access_audit_event.actor_user is '触发操作的用户标识。';
comment on column access_audit_event.actor_name is '触发操作的用户名或展示名。';
comment on column access_audit_event.event_type is '审计事件类型，例如 create、upload、callback_rejected。';
comment on column access_audit_event.event_time is '审计事件发生时间。';
comment on column access_audit_event.event_source is '审计事件来源渠道，例如 header、jwt、system。';
comment on column access_audit_event.event_result is '审计事件结果，例如 success、rejected。';
comment on column access_audit_event.message is '审计事件补充说明。';

comment on table document_runtime_event is '文档运行事件表，记录 callback、保存成功、保存失败等关键运行态事件。';
comment on column document_runtime_event.event_id is '运行事件主键。';
comment on column document_runtime_event.document_id is '关联的内部文档主键。';
comment on column document_runtime_event.event_type is '运行事件类型，例如 callback_received、save_succeeded。';
comment on column document_runtime_event.callback_status is '运行事件关联的 callback 状态码。';
comment on column document_runtime_event.event_message is '运行事件说明信息。';
comment on column document_runtime_event.event_time is '运行事件发生时间。';

comment on table document_editor_session is '文档编辑会话表，记录当前活跃编辑用户与最近会话时间。';
comment on column document_editor_session.session_id is '编辑会话主键。';
comment on column document_editor_session.document_id is '关联的内部文档主键。';
comment on column document_editor_session.tenant_id is '编辑会话所属租户标识。';
comment on column document_editor_session.actor_user is '活跃编辑用户标识。';
comment on column document_editor_session.actor_name is '活跃编辑用户展示名。';
comment on column document_editor_session.opened_time is '编辑会话创建时间。';
comment on column document_editor_session.last_seen_time is '最近一次检测到该编辑会话活跃的时间。';
comment on column document_editor_session.closed_time is '编辑会话显式结束时间，未结束时为空。';
comment on column document_editor_session.created_time is '会话记录创建时间。';
comment on column document_editor_session.updated_time is '会话记录最近更新时间。';
