comment on table document_llm_session is '文档 AI 会话表，记录当前文档下的对话线程和最近快照。';
comment on column document_llm_session.session_id is 'AI 会话主键。';
comment on column document_llm_session.document_id is '关联的内部文档主键。';
comment on column document_llm_session.tenant_id is '会话所属租户。';
comment on column document_llm_session.actor_user is '会话所属用户标识。';
comment on column document_llm_session.title is '会话标题。';
comment on column document_llm_session.last_snapshot_text is '最近一次发送时的选区快照文本。';
comment on column document_llm_session.last_snapshot_is_empty is '最近一次发送是否为空选区。';
comment on column document_llm_session.last_heading_id is '最近一次发送时使用的标题 ID。';
comment on column document_llm_session.last_heading_text is '最近一次发送时使用的标题文本。';
comment on column document_llm_session.created_time is '会话创建时间。';
comment on column document_llm_session.updated_time is '会话最近更新时间。';
comment on column document_llm_session.archived_time is '会话归档时间。';

comment on table document_llm_message is '文档 AI 消息表，记录用户消息、assistant 消息、快照和错误状态。';
comment on column document_llm_message.message_id is '消息主键。';
comment on column document_llm_message.session_id is '所属 AI 会话主键。';
comment on column document_llm_message.document_id is '关联的内部文档主键。';
comment on column document_llm_message.tenant_id is '消息所属租户。';
comment on column document_llm_message.actor_user is '消息所属用户标识。';
comment on column document_llm_message.role is '消息角色，例如 user 或 assistant。';
comment on column document_llm_message.message_text is '用户消息正文。';
comment on column document_llm_message.assistant_text is 'assistant 返回正文。';
comment on column document_llm_message.snapshot_text is '发送时携带的选区快照文本。';
comment on column document_llm_message.snapshot_is_empty is '发送时是否为空选区。';
comment on column document_llm_message.heading_id is '发送时携带的标题 ID。';
comment on column document_llm_message.heading_text is '发送时携带的标题文本。';
comment on column document_llm_message.include_heading is '是否将标题上下文纳入 prompt。';
comment on column document_llm_message.status is '消息状态，例如 pending、completed、failed、cancelled。';
comment on column document_llm_message.retry_of_message_id is '若为重试消息，则指向被重试的消息。';
comment on column document_llm_message.provider_usage_json is '模型 usage 元数据 JSON。';
comment on column document_llm_message.provider_meta_json is '白名单后的 provider 响应元数据 JSON。';
comment on column document_llm_message.finish_reason is '模型返回的 finish reason。';
comment on column document_llm_message.error_code is '稳定 machine-readable 错误码。';
comment on column document_llm_message.created_time is '消息创建时间。';

comment on table document_llm_request is '文档 AI 请求表，记录异步请求状态、取消标记和上游 request 关联。';
comment on column document_llm_request.request_id is 'AI 请求主键。';
comment on column document_llm_request.session_id is '所属 AI 会话主键。';
comment on column document_llm_request.document_id is '关联的内部文档主键。';
comment on column document_llm_request.tenant_id is '请求所属租户。';
comment on column document_llm_request.actor_user is '请求所属用户标识。';
comment on column document_llm_request.user_message_id is '关联的用户消息主键。';
comment on column document_llm_request.assistant_message_id is '关联的 assistant 消息主键。';
comment on column document_llm_request.provider_request_id is '上游 provider request id。';
comment on column document_llm_request.status is '请求状态，例如 in_progress、completed、failed、cancelled。';
comment on column document_llm_request.cancel_requested is '是否已请求取消。';
comment on column document_llm_request.cancel_source is '取消来源，例如 user。';
comment on column document_llm_request.started_time is '请求开始时间。';
comment on column document_llm_request.finished_time is '请求结束时间。';
