server:
  port: 8080

demo:
  onlyoffice:
    document-server-url: http://localhost:8088/
    internal-base-url: http://host.docker.internal:8080
    jwt-secret: onlyoffice-demo-secret-2026-03-09-123456
    default-language: zh
    default-region: zh-CN
    default-user-id: demo-user
    default-user-name: 演示用户
  storage-root: ./storage
